server:
  port: 9001
  servlet:
    context-path: /api/auth-service
spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8888
  threads:
    virtual:
      enabled: true
